id: I4F756466
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T04:59:59+00:00'
last_modified: '2022-06-08T14:12:44.295339+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5787
  title: གསུང་འབུམ། པདྨ་འཕྲིན་ལས་སྙིང་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B818:
      image_group_id: I1KG5790
      title: ''
      total_pages: 430
      order: 1
      base_file: B818.txt
    642B:
      image_group_id: I1KG5791
      title: ''
      total_pages: 460
      order: 2
      base_file: 642B.txt
    FF8A:
      image_group_id: I1KG5792
      title: ''
      total_pages: 428
      order: 3
      base_file: FF8A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
