id: I4F756466
legacy_id: P010520
ocr_import_info:
  bdrc_scan_id: W1KG5787
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T04:56:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:25:24.398026+00:00'
last_modified: 2022-09-01 01:25:59.911447
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5787
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5787
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། པདྨ་འཕྲིན་ལས་སྙིང་པོ།
  author: ཇོ་ཁྱབས་པདྨ་འཕྲིན་ལས་སྙིང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9529194940850451
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG5791:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5791
      total_pages: 460
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG5791.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9531856319209752
    legacy_id: v002
  I1KG5792:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5792
      total_pages: 428
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG5792.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9508482899083496
    legacy_id: v003
  I1KG5790:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5790
      total_pages: 430
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5790.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9541907733146957
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
