id: P010520
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5787
  title: གསུང་འབུམ། པདྨ་འཕྲིན་ལས་སྙིང་པོ།
  author: ''
  volumes:
    9a34f49eb281498b80c07eddae6310f1:
      image_group_id: I1KG5790
      title: ''
      volume_number: 1
      total_pages: 430
      base_file: v001.txt
    667d49e57ac44fb389ce965ee69b2033:
      image_group_id: I1KG5791
      title: ''
      volume_number: 2
      total_pages: 460
      base_file: v002.txt
    5fd49463cc2944ddb8ddabb3293150c5:
      image_group_id: I1KG5792
      title: ''
      volume_number: 3
      total_pages: 428
      base_file: v003.txt
